### ISSUE TITLE
Certificate authentication support

### ISSUE THREAD

**Issue by Raagun** [rtcTo/rtc2gitcli#23]
Hello again,
I have to use certificate login to RTC but plugin seams not to support it. So I added code which I thought should enable it. Branch: [certificate-login](https://github.com/Raagun/rtc2gitcli/tree/certificate-login)
But then I run I get exception:
`Internal error
        at com.ibm.team.filesystem.cli.core.util.StatusHelper.toCLIClientException(StatusHelper.java:721)
        at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:53)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:601)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
        at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:76)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:607)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1384)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: Internal error
        at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:175)
        at to.rtc.cli.migrate.git.MigrateToGit.run(MigrateToGit.java:25)
        at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:51)
        ... 17 more
Caused by: java.lang.RuntimeException: com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: Internal error
        at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:168)
        ... 19 more
Caused by: com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: Internal error
        at com.ibm.team.filesystem.cli.core.util.StatusHelper.toCLIClientException(StatusHelper.java:721)
        at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:53)
        at to.rtc.cli.migrate.command.RtcCommandDelegate.run(RtcCommandDelegate.java:40)
        at to.rtc.cli.migrate.command.AcceptCommandDelegate.run(AcceptCommandDelegate.java:33)
        at to.rtc.cli.migrate.RtcMigrator.acceptAndLoadChangeSet(RtcMigrator.java:114)
        at to.rtc.cli.migrate.RtcMigrator.accept(RtcMigrator.java:95)
        at to.rtc.cli.migrate.RtcMigrator.migrateTag(RtcMigrator.java:50)
        at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:164)
        ... 19 more
Caused by: java.lang.NullPointerException
        at com.ibm.team.filesystem.cli.core.util.RepoUtil.login(RepoUtil.java:648)
        at com.ibm.team.filesystem.cli.core.util.RepoUtil.loginUrlArgAnc(RepoUtil.java:459)
        at com.ibm.team.filesystem.cli.core.util.RepoUtil.loginUrlArgAncestor(RepoUtil.java:561)
        at com.ibm.team.filesystem.cli.client.internal.subcommands.AcceptCmd.generateAcceptParms(AcceptCmd.java:560)
        at com.ibm.team.filesystem.cli.client.internal.subcommands.AcceptCmd.run(AcceptCmd.java:143)
        at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:51)
        ... 25 more`

I looked inside RepoUtil.login() class and it appears to still try to get username and equal it:
`if(repoDTO != null && repoDTO.getContributorItemIdLoggedInContributor() != null) {
                if(info.getUsername().equals(repoDTO.getUserId())) {`

Can you help with this? How to get certificate login support?

Regards
Modestas

**Comment by Raagun** [comment]
Also I quite sure that initially certificate login works because it successfully gets change sets.Exception is thrown then migration of tag starts

**Comment by fbuehlmann** [comment]
Hi 
Which version of RTC cli are you using?
I currently using 5.0.1. I had a look into your mentioned code part of RepoUtlis class. In 5.0.1 the code looks totally ldifferent.
Could you please check of you are able to use accpt and load commands directly with the cli?

Would the migration tool be successful if you run it with --list-tags-only option?

Regards
Florian

**Comment by Raagun** [comment]
I am using 5.0.0 (not 5.0.1). RTC server is that version. And 5.0.1 is incompatible.
Yes I can do all operations (load, accept delete) with my certificate over command line.
Flag --list-tags-only lists all change sets.

**Comment by fbuehlmann** [comment]
If the --list-tags-only is working the main part of the migration tool authentificates over ceritificate.
Looks that the delegation to the accept and load subcommands not successfully work.
Are you sure that you passes the certificate information correctly to the subcommands?

**Comment by Raagun** [comment]
I don't really know. I added code in AcceptCommandDelegate and LoadCommandDelegate and login started to work. I don't saw other places where I should add anything.

**Comment by fbuehlmann** [comment]
And you are sure that your code is working?
There is no other place that need to be modified.
Our systems are not configured to handle certificate authentication. Therefore we are not able to implement this.

**Comment by Raagun** [comment]
Before I added certificate parameter to command it didn't even load change sets. So it works "more". But then I started to get null pointer exceptions from plugin libs.

**Comment by fbuehlmann** [comment]
As I just mentioned before. I'm unable to check this, because I have no system with certificate authentication. 
The NPE is thrown in IBM code. Therefore there must be a problem in your newly added code.
Aren't you able to use username password authentication?
