### ISSUE TITLE
How to install to the command line

### ISSUE THREAD

**Issue by verhasi** [rtcTo/rtc2gitcli#29]
I have successfully cloned and compiled the project. I can even run it from within the eclipse. But when i try to use it from the command line I fail. Actually I tried to put the jar file exported from eclipse to the plugins folder but the sub command migrate-to-git is still unknown. The generated jar contains the META-INF file from the src folder. What else should I do?

Regards,
Istvan

**Comment by reinhapa** [comment]
You may take a look into the [rct2git-docker file](https://github.com/rtcTo/rtc2git-docker/blob/java_plugin/Dockerfile) to see if you put jar into the correct place. Make sure that you have build an actual Eclipse plugin jar first.

**Comment by verhasi** [comment]
Thanks for the suggestion. It was the saved jar file missing the class files as I have only selected the target folder to be exported as it is usual in a maven project. This one is maven project from one side but eclipse project from other side. Finally it is working great.

**Comment by verhasi** [comment]
Oooops unfortunately it failed at help
`C:\Data\tmp\jazz\scmtools\eclipse>scm.exe help migrate-to-git

com.ibm.team.rtc.cli.infrastructure.internal.core.ISubcommandDefinition$LoadOptionsException: org.eclipse.core.runtime.CoreException: Plug-in to.rtc.cli.migrate was unable to load class to.rtc.cli.migrate.git.MigrateToGitOptions.
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandDefinition.getOptions(SubcommandDefinition.java:107)
        at com.ibm.team.rtc.cli.infrastructure.internal.subcommands.HelpCmd.showSubcommand(HelpCmd.java:280)
        at com.ibm.team.rtc.cli.infrastructure.internal.subcommands.HelpCmd.showSubCommand(HelpCmd.java:243)
        at com.ibm.team.rtc.cli.infrastructure.internal.subcommands.HelpCmd.run(HelpCmd.java:112)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:601)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
        at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
Caused by: org.eclipse.core.runtime.CoreException: Plug-in to.rtc.cli.migrate was unable to load class to.rtc.cli.migrate.git.MigrateToGitOptions.
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
        at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:904)
        at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
        at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandDefinition.getOptions(SubcommandDefinition.java:105)
        ... 19 more
Caused by: java.lang.ClassNotFoundException: to.rtc.cli.migrate.git.MigrateToGitOptions
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:506)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:338)
        at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:232)
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1197)
        at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
        ... 23 more
Problem running 'help':
Cannot get option list for migrate-to-git: Plug-in to.rtc.cli.migrate was unable to load class to.rtc.cli.migrate.git.MigrateToGitOptions.

C:\Data\tmp\jazz\scmtools\eclipse>`

even in the rtc2git.jar it is there
![image](https://user-images.githubusercontent.com/2287064/27076734-4e953d68-502e-11e7-9e26-02fc3a325d2b.png)

**Comment by reinhapa** [comment]
@verhasi what version of RTC are you using? Do you got the same problem getting the help within your eclipse development environment?

Unfortunately we do no longer have RTC accessable here, but I will try to cross check this within one of my docker images.

**Comment by verhasi** [comment]
Hi @reinhapa,

I use the version 5.0.2 . In case of the eclipse version there is no such issue, even the migration is running perfectly. Thanks for your help in advance.

Regards,
Istvan

**Comment by reinhapa** [comment]
When running the help command in the docker image
`docker run -it --name rtc2git rtcto/rtc2git:5.0.2`

 I got the correct help output:

```

Help for: scm migrate-to-git

No description available.

Usage: scm migrate-to-git [options] <source-workspace-name> <destination-workspace-name>

  source-workspace-name      - name of the pre configured source RTC workspace
                               that could follow the stream to migrate.
  destination-workspace-name - name of the pre configured RTC workspace that
                               holds the current state of the migration and
                               that follows the source-workspace-name.

Options:
  --certificate arg               - The file that contains the user's login
                                    certificate.
  --smartCard                     - Use the connected smart card for
                                    authentication.
  -d [--directory] arg            - Runs the command in the named directory.
  -L [--list-tags-only]           - List only all tags that would be migrated
                                    but do not migrate them.
  -m [--migrationProperties] arg  - File with migration properties.
  -P [--password] arg             - The password for the repository.
  -r [--repository-uri] arg       - The URI that specifies the location of the
                                    repository.
  -t [--timeout] arg              - Timeout in seconds, default is 900
  -u [--username] arg             - The user name for the repository.
  -U [--update]                   - Update the content of an already migrated
                                    workspace.
```
Seems to be a problem using Windows...

**Comment by verhasi** [comment]
I tried it on Linux with the same result.

` ./jazz/scmtools/eclipse/scm.sh migrate-to-git help
Could not load options for "migrate-to-git":
Plug-in to.rtc.cli.migrate was unable to load class to.rtc.cli.migrate.git.MigrateToGitOptions.
<title></title>
`

so the problem could be in jar generation or META-INF. Could you give me some hint how to package it? It would be nice to use the maven to do it but ....

**Comment by reinhapa** [comment]
@verhasi the with Maven is the first of all that I saw no _simple_ way to get hold on the RTC resources to build upon. You wrote, that you have tried on Linux too and it worked. Do you mean the export process under Linux produces a plugin jar that is working within Linux but not under Windows? Or does is it only not working with a produced JAR under Windows?

**Comment by verhasi** [comment]
> you have tried on Linux too and it worked

No I haven't written it, and it didn't work on Linux. My eclipse is running on Windows and I exported from it the jar file. The same jar failed on both operating system.
In the meantime I have found the solution following your hints with the docker image. Pulled it and investigated the difference between the jar in the docker image and the jar I have exported. The main difference is that in my case the class files were not packaged into a jar file inside the plugin jar. I am going to document the packaging and after it I will close this issue.

Regards,
Istvan

**Comment by reinhapa** [comment]
@verhasi I see, thanks for your investigations 👍

**Comment by verhasi** [comment]
The "documentation" of packaging is: Export the new version of the plugin as shown here
![export_and_workspaceneon_-_plug-in_development_-_cli_extension_meta-inf_manifest_mf_-_eclipse](https://user-images.githubusercontent.com/2287064/35615957-f9f39230-0673-11e8-8428-c5be5f0a0544.png)
No special settings or option is required.

**Comment by ghost** [comment]
@verhasi :need your help on the setup of project in eclipse,can you help

**Comment by verhasi** [comment]
@satish1729-hash Sure I can help you but I propose to create a new ticket for it and provide the details of your problem.

**Comment by ghost** [comment]
Dear Team,

Thanks alot for your response.

I am not clear how to setup source_workspace and target_workspace.

Could you please help to clarify with some example.

**Comment by ghost** [comment]
Also raised new ticket for another error

Maven connector plugin error #71
