### ISSUE TITLE
issue when migration with baseline tagged

### ISSUE THREAD

**Issue by kaiilin** [rtcTo/rtc2gitcli#45]
Hi, I tried to migrate with the baseline tagged. 

So I update the migration.properties to uncomment this line. 
       _rtc.baseline.include=^(.*)$_
and begin to the migration. 

I had run into this error. Could you please help me how to resolve it? I cannot be sure why it says the tag already exists. 
thanks

=====================================================
tag Initial_Baseline_20120405-182919
tagger PersonIdent[RTC 2 git, rtc2git@rtc.to, Mon Apr 16 11:23:36 2018 +0800]

}' already exists
	at org.eclipse.jgit.api.TagCommand.updateTagRef(TagCommand.java:193)
	at org.eclipse.jgit.api.TagCommand.call(TagCommand.java:164)
	at to.rtc.cli.migrate.git.GitMigrator.createTag(GitMigrator.java:481)
	... 21 more
Migration took [13] s
Unexpected exception
com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: java.lang.RuntimeException: Unable to tag
	at com.ibm.team.filesystem.cli.core.util.StatusHelper.toCLIClientException(StatusHelper.java:731)
	at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:53)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:601)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
	at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1384)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Unable to tag
	at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:180)
	at to.rtc.cli.migrate.git.MigrateToGit.run(MigrateToGit.java:25)
	at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:51)
	... 17 more
Caused by: java.lang.RuntimeException: Unable to tag
	at to.rtc.cli.migrate.git.GitMigrator.createTag(GitMigrator.java:485)
	at to.rtc.cli.migrate.RtcMigrator.migrateTag(RtcMigrator.java:75)
	at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:169)
	... 19 more
Caused by: org.eclipse.jgit.api.errors.RefAlreadyExistsException: tag 'Tag={
object ce8910fdca219b92dd55b204e7e2fcec1be6bbd3
type commit
tag Initial_Baseline_20120405-182919
tagger PersonIdent[RTC 2 git, rtc2git@rtc.to, Mon Apr 16 11:23:36 2018 +0800]

}' already exists
	at org.eclipse.jgit.api.TagCommand.updateTagRef(TagCommand.java:193)
	at org.eclipse.jgit.api.TagCommand.call(TagCommand.java:164)
	at to.rtc.cli.migrate.git.GitMigrator.createTag(GitMigrator.java:481)
	... 21 more

**Comment by WtfJoke** [comment]
Hi kaiilin,

Probably multiple baselines gets resolved to the same tag name.
Can you provide a list of your baselines?

You can also check your baselines against method createTagName
https://github.com/rtcTo/rtc2gitcli/blob/master/rtc2git.cli.extension/src/to/rtc/cli/migrate/git/GitMigrator.java#L415

If you can write tests for that it would be cool :)

**Comment by kaiilin** [comment]
@WtfJoke 
I clean up my RTC workspace and git respository and start over. This time it migrates successfully. thanks. I'll close this ticket.
