### ISSUE TITLE
issue with launching configuration rtc2git

### ISSUE THREAD

**Issue by himmakam** [rtcTo/rtc2gitcli#46]
I used scmtools 6.x before. but now am using 5.0.2 and now getting the below error - How can I get rid of this one.

com.ibm.team.rtc.cli.infrastructure.internal.core.ISubcommandDefinition$LoadOptionsException: org.eclipse.core.runtime.CoreException: Plug-in to.rtc.cli.migrate was unable to load class to.rtc.cli.migrate.git.MigrateToGitOptions.
at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandDefinition.getOptions(SubcommandDefinition.java:107)
at com.ibm.team.rtc.cli.infrastructure.internal.subcommands.HelpCmd.showSubcommand(HelpCmd.java:280)
at com.ibm.team.rtc.cli.infrastructure.internal.subcommands.HelpCmd.showSubCommand(HelpCmd.java:243)
at com.ibm.team.rtc.cli.infrastructure.internal.subcommands.HelpCmd.run(HelpCmd.java:112)
at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:601)
at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
at org.eclipse.equinox.launcher.Main.main(Main.java:1384)
Caused by: org.eclipse.core.runtime.CoreException: Plug-in to.rtc.cli.migrate was unable to load class to.rtc.cli.migrate.git.MigrateToGitOptions.
at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:904)
at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandDefinition.getOptions(SubcommandDefinition.java:105)

**Comment by himmakam** [comment]
I created eclipse plugin from src folder , export as Deployable plugins and fragments. and placed the jar in plugins folder. Is this is what needs to be done? or I missed something else here?

**Comment by WtfJoke** [comment]
Do you tried to use the existing eclipse launch config to display the help? 

Have you an error free eclipse workspace?

**Comment by himmakam** [comment]
If I run scm migration-to-git in command line, it is working inspite of the above error. So am assuming am all good for now and so closing this issue
