### ISSUE TITLE
Getting "java.lang.NullPointerException" when running migrate-to-git

### ISSUE THREAD

**Issue by giuli4** [rtcTo/rtc2gitcli#52]
Hello,

when I try to run the command migrate-to-git, I get the following exceptions:

Create the list of baselines
java.lang.NullPointerException
  at to.rtc.cli.migrate.MigrateTo.createTagListFromBaselines(MigrateTo.java:251)
  at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:117)
  at to.rtc.cli.migrate.git.MigrateToGit.run(MigrateToGit.java:25)
  at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:51)
  at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:601)
  at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
  at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
  at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
  at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
  at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
  at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
  at java.lang.reflect.Method.invoke(Method.java:508)
  at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
  at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
  at org.eclipse.equinox.launcher.Main.run(Main.java:1408)

Can someone help me?

Thank you,
Giulia

**Comment by WtfJoke** [comment]
Hi Giulia

Are you using rtc 6+?
Sadly I cant help you. I havent experienced this problem and some users did experience the same/similar problem....

You might want to try rtc2git instead.

**Comment by subham-awasthi** [comment]
Hi Giulia/WtfJoke,

I have debugged this and found the solution.
RCA : There is an empty or erroneous baseline in between that is causing the issue.

If you wish I can check-in the solution.

Thanks & Regards,
Subham

**Comment by ghost** [comment]
@subham-awasthi 
Can you please provide me the solution to overcome this issue. I am also facing the same issue while migrating my code.

**Comment by SwarajyaLakshmiTPRSS** [comment]
> 
> 
> Hi Giulia/WtfJoke,
> 
> I have debugged this and found the solution.
> RCA : There is an empty or erroneous baseline in between that is causing the issue.
> 
> If you wish I can check-in the solution.
> 
> Thanks & Regards,
> Subham

Hi Subham,
We are facing with the same issue while running migrate-to-git . Can you please provide the solution on how you fixed it

**Comment by SwarajyaLakshmiTPRSS** [comment]
> 
> 
> Hi Giulia/WtfJoke,
> 
> I have debugged this and found the solution.
> RCA : There is an empty or erroneous baseline in between that is causing the issue.
> 
> If you wish I can check-in the solution.
> 
> Thanks & Regards,
> Subham

Hi Subham,
We are facing with the same issue while running migrate-to-git . Can you please provide the solution on how you fixed it

**Comment by ghost** [comment]
@ghost:can you plz clarify where we need to place migration.properties so that tool  consider it..i am getting error stating file not available

**Comment by ghost** [comment]
> Hi Giulia/WtfJoke,
> 
> I have debugged this and found the solution.
> RCA : There is an empty or erroneous baseline in between that is causing the issue.
> 
> If you wish I can check-in the solution.
> 
> Thanks & Regards,
> Subham

Can you please provide solution for this,also steps with screenshot to configure source_workspace and target-workspace with examples
