### ISSUE TITLE
Errors with "Add" on migration (folder / file conflicts)

### ISSUE THREAD

**Issue by garret-rempel** [rtcTo/rtc2gitcli#62]
I'm running into 2 folder or file issues when attempting to run the scm migrate-to-git as a plugin.

**1)** If I attempt to run the script from a regular (empty) folder i.e "C:\test" I get the following error:
RuntimeException: "C:\test" is not shared. null at ...
![image](https://user-images.githubusercontent.com/58080071/69434874-1b767600-0d04-11ea-8944-ad858b82b9d3.png)

Full stack trace:
!ENTRY org.eclipse.osgi 4 0 2019-11-22 06:41:45.715
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: com.ibm.team.filesystem.cli.core.util.CLIFileSystemClientException: Status ERROR: com.ibm.team.filesystem.cli.core code=30 "c:\test" is not shared. null
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:143)
	at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
Caused by: com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: com.ibm.team.filesystem.cli.core.util.CLIFileSystemClientException: Status ERROR: com.ibm.team.filesystem.cli.core code=30 "c:\test" is not shared. null
	at com.ibm.team.filesystem.cli.core.util.StatusHelper.toCLIClientException(StatusHelper.java:731)
	at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:53)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:601)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
	... 13 more
Caused by: java.lang.RuntimeException: com.ibm.team.filesystem.cli.core.util.CLIFileSystemClientException: Status ERROR: com.ibm.team.filesystem.cli.core code=30 "c:\test" is not shared. null
	at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:180)
	at to.rtc.cli.migrate.git.MigrateToGit.run(MigrateToGit.java:25)
	at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:51)
	... 16 more
Caused by: com.ibm.team.filesystem.cli.core.util.CLIFileSystemClientException: Status ERROR: com.ibm.team.filesystem.cli.core code=30 "c:\test" is not shared. null
	at com.ibm.team.filesystem.cli.core.util.StatusHelper.createException(StatusHelper.java:403)
	at com.ibm.team.filesystem.cli.core.util.StatusHelper.inappropriateArgument(StatusHelper.java:486)
	at com.ibm.team.filesystem.cli.core.util.RepoUtil.getSandboxPathsAndRegister(RepoUtil.java:1289)
	at com.ibm.team.filesystem.cli.core.util.RepoUtil.getSharesInSandbox(RepoUtil.java:1315)
	at com.ibm.team.filesystem.cli.core.util.RepoUtil.getComponentsInSandbox(RepoUtil.java:1355)
	at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:149)
	... 18 more

**2)** If, however, I attempt to run the command from the SCM tools folder ("C:\Tools\jazz\scmtools\eclipse") I get a different error:
JGitInternalException / IO Exception: The process cannot access the file because another process has locked a portion of the file.
![image](https://user-images.githubusercontent.com/58080071/69435174-ab1c2480-0d04-11ea-9a0b-b3853b68d043.png)

Full stack trace:
!ENTRY org.eclipse.osgi 4 0 2019-11-22 06:46:13.027
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:143)
	at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
Caused by: com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at com.ibm.team.filesystem.cli.core.util.StatusHelper.toCLIClientException(StatusHelper.java:731)
	at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:53)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:601)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
	at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
	... 13 more
Caused by: java.lang.RuntimeException: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:180)
	at to.rtc.cli.migrate.git.MigrateToGit.run(MigrateToGit.java:25)
	at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:51)
	... 16 more
Caused by: org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of add command
	at org.eclipse.jgit.api.AddCommand.call(AddCommand.java:246)
	at to.rtc.cli.migrate.git.GitMigrator.gitCommit(GitMigrator.java:228)
	at to.rtc.cli.migrate.git.GitMigrator.init(GitMigrator.java:435)
	at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:147)
	... 18 more

Any thoughts that might help me overcome these errors? My RTC repository is v5.0.2.

**Comment by WtfJoke** [comment]
Sorry, overlooked your issue. But sadly I dont know how you can overcome these erros. You could try to use rtc2git and see if that works. Or use the docker-version of rtc2gitcli
