### ISSUE TITLE
NullPointerException while fetching history from RTC

### ISSUE THREAD

**Issue by css-inverso** [rtcTo/rtc2gitcli#75]
Hi,

I am using the docker image with scm 5.0.2 to migrate some of our components.
I ran into the following exception during the migration of a specific component.

`[2022-01-31 13:50:47] Initialize RTC connection with connection timeout of 900s
[2022-01-31 13:50:50] Get full history information from RTC. This could take a large amount of time.
[2022-01-31 13:50:50] Create the list of baselines
[2022-01-31 13:50:51] java.lang.NullPointerException
        at to.rtc.cli.migrate.MigrateTo.createTagListFromBaselines(MigrateTo.java:251)
        at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:117)
        at to.rtc.cli.migrate.git.MigrateToGit.run(MigrateToGit.java:25)
        at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:51)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:601)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
        at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1384)
Migration took [3] s
Unexpected exception
com.ibm.team.rtc.cli.infrastructure.internal.core.CLIClientException: java.lang.NullPointerException
        at com.ibm.team.filesystem.cli.core.util.StatusHelper.toCLIClientException(StatusHelper.java:731)
        at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:53)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:601)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.doStart(SubcommandLauncher.java:370)
        at com.ibm.team.rtc.cli.infrastructure.internal.core.SubcommandLauncher.run(SubcommandLauncher.java:130)
        at com.ibm.team.rtc.cli.infrastructure.internal.Application.start(Application.java:41)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:369)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:620)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:575)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1408)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1384)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:180)
        at to.rtc.cli.migrate.git.MigrateToGit.run(MigrateToGit.java:25)
        at com.ibm.team.filesystem.cli.core.AbstractSubcommand.run(AbstractSubcommand.java:51)
        ... 17 more
Caused by: java.lang.NullPointerException
        at to.rtc.cli.migrate.MigrateTo.createTagListFromBaselines(MigrateTo.java:251)
        at to.rtc.cli.migrate.MigrateTo.run(MigrateTo.java:117)
        ... 19 more
Scm:
An error has occurred. See the log file
/var/data/dev/.metadata/.log.`

From what I gather from the code the Baseline Entry doesn't actually have a baseline. Does that mean the entry is empty and can be skipped or is that a bug in scm or rtc respectively?

Thank you in advance for your help.

**Comment by boozacs** [comment]
Did you find a workaround for this error?
